import type { Metadata } from 'next';
import Script from 'next/script';
import Link from 'next/link';
import {
  ArrowRight,
  DollarSign,
  TrendingDown,
  ShieldOff,
  Search,
  Briefcase,
  UserX,
  Handshake,
  BadgeAlert,
  Heart,
  CheckCircle2,
} from 'lucide-react';
import Navbar from '@/components/shared/Navbar';
import Footer from '@/components/shared/Footer';

export const metadata: Metadata = {
  title: 'How Negative Reviews Impact Revenue, Trust & Growth | Reach Them AI',
  description:
    'Discover how negative reviews impact your business revenue, customer trust, search rankings, and long-term growth. Data-backed insights from Harvard, Womply, BrightLocal, and more.',
  keywords: [
    'negative reviews impact business',
    'how negative reviews affect revenue',
    'bad reviews cost',
    'negative review statistics',
    'review impact on sales',
    'online reviews business impact',
    'negative reviews SEO',
  ],
  openGraph: {
    title: 'How Negative Reviews Impact Revenue, Trust & Growth | Reach Them AI',
    description:
      'Data-backed analysis of how negative reviews cost businesses revenue, erode customer trust, hurt search visibility, and stunt growth.',
    images: ['/featured.png'],
    type: 'article',
  },
};

const articleJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Article',
  headline: 'How Negative Reviews Impact Revenue, Trust & Growth',
  description:
    'Data-backed analysis of how negative reviews cost businesses revenue, erode customer trust, hurt search visibility, and stunt growth.',
  author: {
    '@type': 'Organization',
    name: 'Reach Them AI',
    url: 'https://reachthem.ai',
  },
  publisher: {
    '@type': 'Organization',
    name: 'Reach Them AI',
    url: 'https://reachthem.ai',
  },
  mainEntityOfPage: {
    '@type': 'WebPage',
    '@id': 'https://reachthem.ai/negative-reviews-impact',
  },
};

const revenueStats = [
  {
    icon: UserX,
    value: '30',
    suffix: ' customers lost',
    label: 'per unanswered negative review. A single 1-star review on Google can drive away an average of 30 potential customers who would have otherwise considered your business.',
    source: 'Harvard Business Review',
  },
  {
    icon: TrendingDown,
    value: '33%',
    suffix: ' less revenue',
    label: 'generated by businesses with star ratings between 1.0 and 1.5 compared to the industry average. Low ratings do not just reduce leads — they collapse your revenue floor.',
    source: 'Womply',
  },
  {
    icon: DollarSign,
    value: '22%',
    suffix: ' conversion decrease',
    label: 'when a single negative article appears on page one of search results for your brand. Two negative articles push that figure to 44%, and three can mean a 59% drop.',
    source: 'Moz Research',
  },
  {
    icon: ArrowRight,
    value: '18%',
    suffix: ' revenue increase',
    label: 'observed when businesses improve their average rating from 3 stars to 5 stars. Every half-star improvement translates to measurable revenue growth.',
    source: 'Harvard Business School',
  },
];

const trustStats = [
  {
    icon: ShieldOff,
    value: '94%',
    label: 'of consumers say a negative review has convinced them to avoid a business entirely. For most customers, even one or two bad reviews is enough to trigger a "no" decision — they simply move on to the next option.',
    source: 'ReviewTrackers',
  },
  {
    icon: Heart,
    value: '40:1',
    label: 'positive-to-negative recovery ratio. It takes approximately 40 positive customer experiences to undo the reputational damage caused by a single negative review. Negative experiences are psychologically more memorable and carry disproportionate weight.',
    source: 'Inc. Magazine',
  },
  {
    icon: BadgeAlert,
    value: '86%',
    label: 'of people hesitate to purchase from a business that has negative online reviews, even when the product or service itself meets their needs. The reviews become a proxy for trustworthiness.',
    source: 'BrightLocal',
  },
];

export default function NegativeReviewsImpactPage() {
  return (
    <>
      <Script
        id="negative-reviews-article-jsonld"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }}
      />

      <div className="min-h-screen bg-white dark:bg-slate-900 negative-reviews-impact-page">
        <Navbar background="white" />
        <main>
          {/* Hero */}
          <section className="pt-32 pb-20 bg-white dark:bg-slate-900">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
              <span className="inline-block px-3 py-1 rounded-full bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400 text-sm font-medium mb-6">
                Data-Backed Analysis
              </span>
              <h1 className="text-5xl md:text-6xl font-bold tracking-tight text-slate-900 dark:text-white negative-reviews-impact-h1">
                How Negative Reviews Impact Revenue, Trust &amp; Growth
              </h1>
              <p className="mt-6 text-xl text-slate-600 dark:text-slate-400 leading-relaxed max-w-3xl mx-auto">
                Negative reviews are not merely an inconvenience — they are a measurable drain on
                your bottom line. This guide breaks down the real-world financial, trust, and growth
                consequences backed by research from Harvard, BrightLocal, Womply, and Moz.
              </p>
            </div>
          </section>

          {/* Revenue Impact */}
          <section className="py-24 bg-[#182825] text-white">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-lg bg-red-500/20 flex items-center justify-center">
                  <DollarSign className="h-5 w-5 text-red-400" />
                </div>
                <h2 className="text-3xl md:text-4xl font-bold">The Revenue Impact</h2>
              </div>
              <p className="text-lg text-slate-300 leading-relaxed mb-10">
                Revenue loss from negative reviews is not hypothetical. Academic studies and
                industry research have quantified the direct financial damage that bad reviews
                inflict on businesses of every size and category.
              </p>
              <div className="grid gap-6">
                {revenueStats.map((stat) => (
                  <div
                    key={stat.value}
                    className="p-6 rounded-2xl bg-white/5 border border-white/10"
                  >
                    <div className="flex items-center gap-4 mb-3">
                      <div className="w-10 h-10 rounded-lg bg-primary-500/20 flex items-center justify-center">
                        <stat.icon className="h-5 w-5 text-primary-400" />
                      </div>
                      <div>
                        <span className="text-3xl font-extrabold text-primary-400">
                          {stat.value}
                        </span>
                        <span className="text-lg font-semibold text-slate-300">{stat.suffix}</span>
                      </div>
                    </div>
                    <p className="text-slate-300 leading-relaxed">{stat.label}</p>
                    <p className="mt-2 text-xs text-slate-500">— {stat.source}</p>
                  </div>
                ))}
              </div>
              <p className="mt-8 text-lg text-slate-300 leading-relaxed">
                These figures make one thing clear: negative reviews are not a vanity metric problem.
                They translate directly into lost bookings, abandoned carts, and missed phone calls
                — measurable revenue that flows to your competitors instead of your business.
              </p>
            </div>
          </section>

          {/* Trust Erosion */}
          <section className="py-24 bg-white dark:bg-slate-900">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-lg bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center">
                  <ShieldOff className="h-5 w-5 text-amber-600 dark:text-amber-400" />
                </div>
                <h2 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white">
                  How Trust Erodes
                </h2>
              </div>
              <p className="mt-4 text-lg text-slate-600 dark:text-slate-400 leading-relaxed">
                Trust is the foundation of every purchasing decision. When negative reviews appear,
                they do not just inform — they trigger deep psychological responses that are
                difficult to reverse. Consumers give significantly more weight to negative
                information than positive information, a phenomenon psychologists call{' '}
                <em>negativity bias</em>.
              </p>
              <div className="mt-10 grid gap-6">
                {trustStats.map((stat) => (
                  <div
                    key={stat.value}
                    className="rounded-2xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 p-6 flex items-start gap-5"
                  >
                    <div className="flex-shrink-0 w-12 h-12 rounded-xl bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center">
                      <stat.icon className="h-6 w-6 text-amber-600 dark:text-amber-400" />
                    </div>
                    <div>
                      <div className="text-3xl font-extrabold text-amber-600 dark:text-amber-400">
                        {stat.value}
                      </div>
                      <p className="mt-1 text-slate-600 dark:text-slate-400 leading-relaxed">
                        {stat.label}
                      </p>
                      <p className="mt-2 text-xs text-slate-500">— {stat.source}</p>
                    </div>
                  </div>
                ))}
              </div>
              <p className="mt-8 text-lg text-slate-600 dark:text-slate-400 leading-relaxed">
                Rebuilding trust after it has been damaged is exponentially harder — and more
                expensive — than maintaining it. The businesses that invest in proactive reputation
                management avoid the costly cycle of damage and recovery entirely.
              </p>
            </div>
          </section>

          {/* Search Visibility Impact */}
          <section className="py-24 bg-slate-50 dark:bg-slate-800/50">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-lg bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center">
                  <Search className="h-5 w-5 text-blue-600 dark:text-blue-400" />
                </div>
                <h2 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white">
                  Search Visibility Impact
                </h2>
              </div>
              <p className="mt-4 text-lg text-slate-600 dark:text-slate-400 leading-relaxed">
                Google&apos;s algorithm explicitly factors review signals — volume, velocity,
                diversity, and sentiment — into local search rankings. Negative reviews do not just
                hurt perception; they can push your business lower in search results, reducing
                organic visibility at the exact moment customers are ready to buy.
              </p>
              <div className="mt-8 space-y-6">
                <div className="rounded-2xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 p-6">
                  <h3 className="text-xl font-semibold text-slate-900 dark:text-white">
                    Google Maps &amp; Local Pack Rankings
                  </h3>
                  <p className="mt-2 text-slate-600 dark:text-slate-400 leading-relaxed">
                    Google&apos;s local pack (the top 3 map results) heavily weights review quality
                    and recency. Businesses with lower average ratings and unresolved negative
                    reviews are pushed below competitors with stronger review profiles. Since 46% of
                    all Google searches have local intent, losing visibility in the local pack means
                    losing nearly half of your potential audience.
                  </p>
                </div>
                <div className="rounded-2xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 p-6">
                  <h3 className="text-xl font-semibold text-slate-900 dark:text-white">
                    Negative Sentiment in Search Results
                  </h3>
                  <p className="mt-2 text-slate-600 dark:text-slate-400 leading-relaxed">
                    When customers search your brand name, Google surfaces review snippets, rating
                    stars, and third-party content. If negative articles, complaint board threads, or
                    low-rated review profiles dominate page one, your brand narrative is being
                    written by your worst experiences instead of your best. This is compounded by
                    the fact that 75% of users never scroll past the first page of results.
                  </p>
                </div>
                <div className="rounded-2xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 p-6">
                  <h3 className="text-xl font-semibold text-slate-900 dark:text-white">
                    Click-Through Rate Decline
                  </h3>
                  <p className="mt-2 text-slate-600 dark:text-slate-400 leading-relaxed">
                    Rich snippets that display star ratings directly in search results influence
                    click behavior before users even visit your website. A business showing 3.2
                    stars next to a competitor showing 4.7 stars will receive significantly fewer
                    clicks — Google data suggests the difference can be as high as 25% lower CTR for
                    listings with ratings below 4 stars.
                  </p>
                </div>
              </div>
            </div>
          </section>

          {/* Growth Impact */}
          <section className="py-24 bg-white dark:bg-slate-900">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-lg bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center">
                  <Briefcase className="h-5 w-5 text-purple-600 dark:text-purple-400" />
                </div>
                <h2 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white">
                  Long-Term Growth Consequences
                </h2>
              </div>
              <p className="mt-4 text-lg text-slate-600 dark:text-slate-400 leading-relaxed">
                Beyond immediate revenue and trust, negative reviews create compounding damage to
                your long-term growth trajectory. The effects ripple through hiring, partnerships,
                and overall brand equity.
              </p>
              <div className="mt-8 grid sm:grid-cols-3 gap-6">
                {[
                  {
                    icon: UserX,
                    title: 'Hiring Challenges',
                    text: 'Top talent researches employers online before applying. Companies with negative Glassdoor and Indeed reviews experience 50% fewer qualified applicants and must offer 10% higher salaries to compensate for reputational risk.',
                  },
                  {
                    icon: Handshake,
                    title: 'Partnership Barriers',
                    text: 'Potential partners and investors perform due diligence that includes a simple Google search. Negative reviews and articles create friction, delay deals, and can eliminate partnership opportunities entirely.',
                  },
                  {
                    icon: BadgeAlert,
                    title: 'Brand Equity Erosion',
                    text: 'Brand value is an intangible asset that takes years to build and moments to damage. Persistent negative reviews chip away at the premium customers are willing to pay, forcing price-based competition.',
                  },
                ].map((item) => (
                  <div
                    key={item.title}
                    className="rounded-2xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 p-6"
                  >
                    <div className="w-10 h-10 rounded-lg bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center mb-4">
                      <item.icon className="h-5 w-5 text-purple-600 dark:text-purple-400" />
                    </div>
                    <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
                      {item.title}
                    </h3>
                    <p className="mt-2 text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                      {item.text}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </section>

          {/* The Path Forward */}
          <section className="py-24 bg-slate-50 dark:bg-slate-800/50">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-lg bg-green-100 dark:bg-green-900/30 flex items-center justify-center">
                  <CheckCircle2 className="h-5 w-5 text-green-600 dark:text-green-400" />
                </div>
                <h2 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white">
                  The Path Forward: Proactive Reputation Management
                </h2>
              </div>
              <p className="mt-4 text-lg text-slate-600 dark:text-slate-400 leading-relaxed">
                The data is clear — negative reviews are not a problem you can ignore and hope will
                go away. But the good news is that businesses that take a proactive approach see
                dramatic improvements:
              </p>
              <ul className="mt-6 space-y-4">
                {[
                  'Identify and remove policy-violating reviews before they accumulate and damage your average rating.',
                  'Respond to every review — positive and negative — within 24 hours to demonstrate accountability and care.',
                  'Monitor your brand across all platforms in real time so you are never caught off guard by emerging issues.',
                  'Build a steady stream of authentic positive reviews that reflect your true customer experience.',
                  'Invest in content and SEO strategies that ensure your brand story dominates search results, not your worst day.',
                ].map((item) => (
                  <li key={item} className="flex items-start gap-3">
                    <CheckCircle2 className="mt-1 h-5 w-5 flex-shrink-0 text-green-600 dark:text-green-400" />
                    <span className="text-lg text-slate-600 dark:text-slate-400 leading-relaxed">
                      {item}
                    </span>
                  </li>
                ))}
              </ul>
              <p className="mt-8 text-lg text-slate-600 dark:text-slate-400 leading-relaxed">
                Want to understand the broader strategy?{' '}
                <Link
                  href="/what-is-online-reputation-management"
                  className="text-primary-600 dark:text-primary-400 font-medium hover:underline"
                >
                  Read our complete guide to Online Reputation Management
                </Link>{' '}
                for a deep dive into every component of an effective ORM program.
              </p>
            </div>
          </section>

          {/* CTA */}
          <section className="py-24 bg-[#182825] text-white">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
              <h2 className="text-3xl md:text-4xl font-bold">
                Stop Letting Negative Reviews Cost You Customers
              </h2>
              <p className="mt-4 text-lg text-slate-300 max-w-2xl mx-auto">
                Every day without a reputation strategy is a day your competitors benefit from your
                negative reviews. Get a free assessment and find out how many of your harmful
                reviews qualify for removal.
              </p>
              <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
                <Link
                  href="/free-assessment"
                  className="inline-flex items-center px-8 py-4 rounded-xl bg-primary-600 text-white font-semibold hover:bg-primary-500 transition-all"
                >
                  Get Your Free Assessment
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
                <Link
                  href="/"
                  className="inline-flex items-center px-8 py-4 rounded-xl bg-white/10 text-white font-semibold hover:bg-white/20 transition-all"
                >
                  Back to Home
                </Link>
              </div>
            </div>
          </section>
        </main>
        <Footer />
      </div>
    </>
  );
}
